import type { Metadata } from 'next';

import Footer from '@/components/ui/footer';
import Header from '@/components/ui/header/header';

import { SITE_NAME } from '@/shared/constants/seo-constants';

import './globals.css';

export const metadata: Metadata = {
	title: {
		absolute: SITE_NAME,
		template: `%s | ${SITE_NAME}`,
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`antialiased`}>
				<Header />
				<main className='bg-background-white flex-1'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
